config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  devise_for :users 

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'  
  end

  resources :user do 
    resources :books do 
      resources :comments 
    end
  end
  
  resources :authors do 
    collection do
      post :update_user_role
    end
  end

  resources :books do
    post 'likes', to: 'likes#create'
  end


  # Define cyour application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "books#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :book
	belongs_to :user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
    @comment = Comment.new
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_book_url(@comment.book.user, @comment.book), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to user_book_comment_url(@comment.book.user, @comment.book), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:post,:user_id,:book_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Post:</strong>
    <%= comment.post %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_for [current_user, @comment.book, @comment] do |form| %>
  <!-- <%# if @comment.errors.any? %>
    <div style="color: red">
      <h2><%#= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <%# comment.errors.each do |error| %>
          <li><%#= error.full_message %></li>
        <%# end %>
      </ul>
    </div>
  <%# end %> -->                
                <div class="bg-light p-2">
                    <div class="d-flex flex-row align-items-start"><img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40">
                        <%= form.text_area :post ,class:"form-control ml-1 shadow-none textarea"%>
                        <%= form.hidden_field :book_id ,value:@book.id%>
                        <%= form.hidden_field :user_id ,value:current_user.id%>
                    </div>
                    <div class="actions mt-2 text-right">
                      <%= form.submit class:"btn btn-primary btn-sm shadow-none"%>
                      <%= link_to "Delete", user_book_path(@book),class:"btn btn-outline-primary btn-sm ml-1 shadow-none", method: :delete, data: { confirm: "Are you sure?" } %>
                    </div>
                </div>
    <% end %>
</div>

app/views/comments/_view.html.erb
<div class="bg-primary p-2 text-dark-50">
    <div class="d-flex flex-row user-info"><%=image_tag "default_usr.jpeg", width:"40" ,class:"rounded-circle"%>
        <div class="d-flex flex-column justify-content-start ml-2"><span class="d-block font-weight-bold name"><%=current_user.email%></span><span class="date text-black-50">Shared publicly</span></div>
    </div>
    <div class="mt-2">
        <p class="comment-text"><%= render @book.comments%></p>
    </div>
</div>
<div class="bg-white">
<div class="d-flex flex-row fs-12">
  <div class="like p-2 cursor"><i class="fa fa-thumbs-o-up">hi</i>
    <span class="ml-1">
       
    </span>
  </div>
  <div class="like p-2 cursor"><i class="fa fa-commenting-o"></i>
    <span class="ml-1">Comment</span>
  </div>
  <div class="like p-2 cursor"><i class="fa fa-share"></i>
    <span class="ml-1">Share</span>
  </div>
</div>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment ,class:"btn btn-info %> |
  <%= link_to "Back to comments", comments_path,class:"btn btn-warning" %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", user_book_comments_path(comment),class:"btn btn-info  %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_user_book_comment_path,,class:"btn btn-primary"  %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", book: @book, comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path, class:"btn btn-warning" %>
</div>

app/views/comments/show.html.erb
<%= render @comment %></p>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) , class:"btn btn-primary"%> |
  <%= link_to "Back to comments", comments_path , class:"btn btn-warning"%>

  <%= button_to "Destroy this comment", @comment,, class:"btn btn-danger", method: :delete %>
</div>