config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  devise_for :users 

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'  
  end

  resources :user do 
    resources :books do 
      resources :comments 
    end
  end
  
  resources :authors do 
    collection do
      post :update_user_role
    end
  end

  resources :books do
    post 'likes', to: 'likes#create'
  end


  # Define cyour application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "books#index"
end

app/models/author.rb
class Author < ApplicationRecord
	# belongs_to :user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # before_action :authenticate_user!,  except: [:index, :show]
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  def update_user_role
    byebug
    current_user.update(role: 'author', about: params[:about], name: params[:name])
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :about, :user_id)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <div class="card-body mb-3">
  <%= link_to image_tag('default_usr.jpg',style: "width:150px;border-radius:50%;border:2px;solid:#0d6efd;"),author,class:'mb-3'%>
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, url: update_user_role_path do |form| %>

<!-- <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
      </div>
    </div>
    <div class="col">
      <div class="form-outline">
        
      </div>
    </div>
  </div>
 -->
  <!-- Text input -->
  <div class="form-outline mb-4">
    <%= form.label :"Author's_Name", style: "display: block" %>
        <%= form.text_field :name , class:"form-control"%>
  </div>

  <!-- Text input -->
  <div class="form-outline mb-4">
        <%= form.label :About, style: "display: block" %>
        <%= form.text_area :about,class:"form-control",rows: "4"%>
         <span class="form-text">
            <i>[must be 50 characters long]</i>
        </span>
  </div>


  <div class="form-group mb-3" align="center">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author, class:""%> |
  <%= link_to "Back to authors", authors_path, class:""%>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>
<br />
<div class="mt-5 mb-3" align="right">
<%= link_to "Modify", edit_user_registration_path,style: 'width:150px;',class:"btn btn-primary"%>
</div>
<div class="card">
</div>

app/views/authors/new.html.erb
<h1>Author</h1>

<%= render "form", author: @author %>
<%= link_to "Back to authors", authors_path, class:"btn btn-dark text-white" %>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>


 <%= render @author %>
 <div class="card mb-3">
    <h4><%= @author.name %></h4>
    <h6><%= @author.about %></h6>
  </div>

<br />
<div class="row">
<div class="col"><%= link_to "Edit this author", edit_author_path(@author), class:"btn btn-info text-white"%></div>
<div class="col"><%= link_to "Back to authors", authors_path, class:"btn btn-warning"%></div>
<div class="col"><%= button_to "Destroy this author", @author,class:"btn btn-danger", method: :delete%></div>
</div>