config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  devise_for :users 

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'  
  end

  resources :user do 
    resources :books do 
      resources :comments 
    end
  end
  
  resources :authors do 
    collection do
      post :update_user_role
    end
  end

  resources :books do
    post 'likes', to: 'likes#create'
  end


  # Define cyour application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "books#index"
end

app/views/shared/_header.html.erb
<header class="bg-dark py mt-1">
      <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
          <div class="col-lg-8 col-xl-7 col-xxl-6">
            <div class="my-5 text-center text-xl-start">
              <h1 class="display-5 fw-bolder text-white mb-2">BookStore App</h1>
              <p class="lead fw-normal text-white-50 mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit! </p>
            </div>
          </div>
          <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"></div>
        </div>
      </div>
</header>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to "Book Page", user_books_path(current_user.books), class:"navbar-brand" if user_signed_in?%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <%if user_signed_in?%>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_out">Logout</a>
        </li>
        <%else%>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in">Log-In</a>
        </li>
        <li class="nav-item">
          <%= link_to "New book", new_user_book_path, class:"nav-link" if user_signed_in?%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/comments" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Comment
          </a>
          <ul class="dropdown-menu">
            <li>
                <%= link_to "Book Page", user_books_path(current_user.books), class:"dropdown-item" if user_signed_in?%>
            </li>
            <li><a class="dropdown-item" href="/comments">Comment Log</a></li>
            <li><hr class="dropdown-divider"></li>
            <!-- <li><a class="dropdown-item" href="#"></a></li> -->
          </ul>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="#">Comming Soon</a>
        </li>
        <%end%>
      </ul> 
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>